name: Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Flake8 linting
        run: |
          flake8 .
      - name: Black code matters
        run: |
          black . --check
  trigger_timer:
    runs-on: ubuntu-20.04 
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v2
      - name: Trigger timer
=======
    - uses: actions/checkout@v2
    - name: Trigger timer
    - shell: bash
>>>>>>> c58e809f0513dad3974a7e944df8ec600b070c7e
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./github/workflows/trigger_timer.sh