name: Timer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trigger_timer:
    runs-on: ubuntu-20.04 
    steps:
      - uses: actions/checkout@v2
      - name: Check added/modified files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}